### PR TITLE
fix(arc-saas): disable button after submit the tenant 

### LINKED ISSUE #73: @arc-saas:submit button should be disabled on submitting the post
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Deepika516**
GH-73

## Description
Disable button after submit the tenant on Tenant Registration component

Fixes #73 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Surbhi-sharma1 — APPROVED** [review]

File: projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.ts [hunk 1]
```diff
@@ -142,6 +144,7 @@ export class TenantRegistrationComponent {
       this.onBoardingService.registerTenant(user).subscribe(
         () => {
           this.toastrService.show('Tenant Added , successfully');
+          this.isSubmitting = false;
```
Comment (yeshamavani) [inline projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.ts:147]: why is this needed @Surbhi-sharma1

**Review by yeshamavani — CHANGES_REQUESTED** [review]

File: projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.ts (hunk 1 above)
Comment (Surbhi-sharma1) [reply projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.ts]: Removed
