### PR TITLE
fix(arc-saas): fix cognito logout

### LINKED ISSUE #48: saas-ui:fix cognito logout
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Surbhi-sharma1**
fix cognito logout

GH-48

## Description

fix cognito logout

Fixes #48 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: projects/saas-ui/src/app/main/main.component.ts [hunk 1]
```diff
@@ -93,9 +93,13 @@ export class MainComponent
...
             .logout()
-            .pipe(concatMap(async () => await this.authService.logoutCognito()))
-            .subscribe();
-          console.log('login works');
+            .pipe(
+              concatMap(async () => await this.authService.logout()),
+              tap(() => this.authService.logoutCognito()),
+            )
+            .subscribe(() => {
+              console.log('login works');
```
Comment (yeshamavani) [inline projects/saas-ui/src/app/main/main.component.ts:101]: unnecessary console

**Review by yeshamavani — APPROVED** [review]
