### PR TITLE
(Arc-Saas):Update the feature when edit the plan

### LINKED ISSUE #91: (Arc-SaaS):Feature needs to update when we edit plan
**Describe the bug**
Feature needs to update when we edit plan

### PR DESCRIPTION
**Pull request by Deepika516**
## Description
Update the feature when edit the plan

Fixes #91 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by yeshamavani** [comment]
Is this tested ? @Deepika516

**Comment by Deepika516** [comment]
> Is this tested ? @Deepika516

Yes Mam tested

File: projects/saas-ui/src/app/main/components/add-plan/add-plan.component.ts [hunk 1]
```diff
@@ -252,20 +252,21 @@ export class AddPlanComponent implements OnInit {
...
-            .filter(
-              key =>
-                featuresGroup.get(key)?.value !== null &&
-                featuresGroup.get(key)?.value !== '',
-            )
+            // .filter(
+            //   key =>
+            //     featuresGroup.get(key)?.value !== null &&
+            //     featuresGroup.get(key)?.value !== '',
+            // )
```
Comment (yeshamavani) [inline projects/saas-ui/src/app/main/components/add-plan/add-plan.component.ts:259]: remove commented code

**Review by yeshamavani — CHANGES_REQUESTED** [review]

**Review by yeshamavani — APPROVED** [review]
